### ISSUE TITLE
CPUFREQ is incorrectly mandatory for IMX6

### ISSUE THREAD

**Issue by fira** [SolidRun/linux-fslc#21]
I'm using an IMX6 with Xenomai, and using CPUFREQ together with Xenomai is majorly discouraged as it can cause a number of problems. I attempted to disable it to be met with this during configure: 

warning: (SOC_IMX6) selects ARM_IMX6Q_CPUFREQ which has unmet direct dependencies (ARCH_HAS_CPUFREQ && CPU_FREQ && ARM && ARCH_MXC && REGULATOR_ANATOP)

And eventually a build failure as some part of the code was using a CPUFREQ specific constant regardless of it being enabled or not. Surrounding it with #ifdef solved it -- and doesn't seem to cause any other problem.

**Comment by linux4kix** [comment]
Thank you for reporting this, but it is not something I intend to fix.
This is a kernel that is designed specifically for SolidRun customers.
While we do accept community contributions some decisions are made in the
best interest of our customers.  We do believe that cpufreq is mandatory
for our iMX6 microsoms because it is the only cooling mechanisms that are
available for our hardware.

Unless you have an active cooling device I would highly recommend you do
not run the iMX6 SOC without cpufreq scaling enabled even then I would
highly recommend you do leave it enabled.  If you do not want the cpu
scaling so much then you can use another scaling governor that keeps a more
constant frequency.
